services:
  web:
    image: ${IMAGE:-ombudsdan/banjo-hootson-react}:${IMAGE_VERSION:-dev}
    ports:
      - "${DOCKER_COMPOSE_IMAGE_PORT:-8082}:8080"
    env_file:
      - .env
    restart: unless-stopped
