name: Sync develop after main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sync-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch origin

      - name: Checkout develop branch
        run: git checkout develop

      - name: Merge main into develop
        run: |
          git merge --ff-only origin/main || echo "Merge conflict — manual resolution required."

      - name: Push develop branch
        run: |
          git push origin develop || echo "Push failed — likely due to merge conflict."
